{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersExternalAnnotations",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jdt",
          "module": "org.eclipse.jdt.annotation",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vegardit.no-npe",
          "module": "no-npe-eea-java-21",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.26.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.26.0.jar",
          "size": 39391,
          "sha512": "6c17db77439ef19b06df6eebd53e1d65dfdb7416eed20c71cfec695a79745390fbb7c3bd31e96e638fbcc5e0dcde56d7f0f0cbf506329fd8fbf83564d76bf6d2",
          "sha256": "16d5f54aafa8bb8897ad49c068df76f5cdf3e214bfcd9a0c6c5ae2663116ea92",
          "sha1": "327165c17ca16b6877c9a29167f4f4679b9834ca",
          "md5": "e8d906e46d65bde0cb36db95fb67d4d2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.26.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.26.0.jar",
          "size": 39391,
          "sha512": "6c17db77439ef19b06df6eebd53e1d65dfdb7416eed20c71cfec695a79745390fbb7c3bd31e96e638fbcc5e0dcde56d7f0f0cbf506329fd8fbf83564d76bf6d2",
          "sha256": "16d5f54aafa8bb8897ad49c068df76f5cdf3e214bfcd9a0c6c5ae2663116ea92",
          "sha1": "327165c17ca16b6877c9a29167f4f4679b9834ca",
          "md5": "e8d906e46d65bde0cb36db95fb67d4d2"
        }
      ]
    }
  ]
}
