{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersMain",
    "version": "2.23.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.23.1"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.23.1.jar",
          "url": "ShopkeepersMain-2.23.1.jar",
          "size": 1839483,
          "sha512": "1cf5268ffaf7949a22039ee8148c0c6dabdfeb3c3ed15d89d5c9325c1aa8a32c5746517c21aaf06ae5c0710ab8476dc50edfbf7294f83550d86b0389abb5bea7",
          "sha256": "eeb7f9bbb0c995ed609558bd618c5922582e7ce411cb580821911781ba78db6a",
          "sha1": "9924312a99a5c7d9d02c025a9bf623e803d0839c",
          "md5": "67fd655914ce6ed4e078ecca0718231a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.23.1"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "com.sk89q.worldedit.worldedit-libs",
              "module": "core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.23.1.jar",
          "url": "ShopkeepersMain-2.23.1.jar",
          "size": 1839483,
          "sha512": "1cf5268ffaf7949a22039ee8148c0c6dabdfeb3c3ed15d89d5c9325c1aa8a32c5746517c21aaf06ae5c0710ab8476dc50edfbf7294f83550d86b0389abb5bea7",
          "sha256": "eeb7f9bbb0c995ed609558bd618c5922582e7ce411cb580821911781ba78db6a",
          "sha1": "9924312a99a5c7d9d02c025a9bf623e803d0839c",
          "md5": "67fd655914ce6ed4e078ecca0718231a"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersMain-2.23.1.jar",
          "url": "ShopkeepersMain-2.23.1.jar",
          "size": 1839483,
          "sha512": "1cf5268ffaf7949a22039ee8148c0c6dabdfeb3c3ed15d89d5c9325c1aa8a32c5746517c21aaf06ae5c0710ab8476dc50edfbf7294f83550d86b0389abb5bea7",
          "sha256": "eeb7f9bbb0c995ed609558bd618c5922582e7ce411cb580821911781ba78db6a",
          "sha1": "9924312a99a5c7d9d02c025a9bf623e803d0839c",
          "md5": "67fd655914ce6ed4e078ecca0718231a"
        }
      ]
    }
  ]
}
