{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersMain",
    "version": "2.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.27.0"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.27.0.jar",
          "url": "ShopkeepersMain-2.27.0.jar",
          "size": 2152135,
          "sha512": "925d78c336ce2b20cb0b8e461fb73e09c510b187147fb16699784c1ea1e26271b96a89979d2790fb0278e3b0ea3add22f70bf61a803bc434530ea51639318699",
          "sha256": "3b67db89f401838298b6475562836271814ec5bb2c6b164adc7564b905d12f3d",
          "sha1": "3cbe0eb99c997bba2a6c942c09e9549222e98868",
          "md5": "7d92a1288f922ad16cdc58bf427ef94e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.27.0"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "com.sk89q.worldedit.worldedit-libs",
              "module": "core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.27.0.jar",
          "url": "ShopkeepersMain-2.27.0.jar",
          "size": 2152135,
          "sha512": "925d78c336ce2b20cb0b8e461fb73e09c510b187147fb16699784c1ea1e26271b96a89979d2790fb0278e3b0ea3add22f70bf61a803bc434530ea51639318699",
          "sha256": "3b67db89f401838298b6475562836271814ec5bb2c6b164adc7564b905d12f3d",
          "sha1": "3cbe0eb99c997bba2a6c942c09e9549222e98868",
          "md5": "7d92a1288f922ad16cdc58bf427ef94e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersMain-2.27.0.jar",
          "url": "ShopkeepersMain-2.27.0.jar",
          "size": 2152135,
          "sha512": "925d78c336ce2b20cb0b8e461fb73e09c510b187147fb16699784c1ea1e26271b96a89979d2790fb0278e3b0ea3add22f70bf61a803bc434530ea51639318699",
          "sha256": "3b67db89f401838298b6475562836271814ec5bb2c6b164adc7564b905d12f3d",
          "sha1": "3cbe0eb99c997bba2a6c942c09e9549222e98868",
          "md5": "7d92a1288f922ad16cdc58bf427ef94e"
        }
      ]
    }
  ]
}
