{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.23.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.23.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.23.0.jar",
          "url": "Shopkeepers-2.23.0.jar",
          "size": 1899745,
          "sha512": "9eb01497785f6df530def2355a55f45dcedf3c17601a6a09403eb1d6c20f41badfa7e75636ffd4099aa1667e00f7e824476a1cfe3b186c54c16f8e8877336886",
          "sha256": "20588faf8ac5387eeddc863aeb7b3c581379c160d0b86d2b5358cbeb5c225ab0",
          "sha1": "765720685f65cbe1d7b8102ba535302088acb9d8",
          "md5": "4308c78b227817ed3fca0f8a529e7e17"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.23.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.23.0.jar",
          "url": "Shopkeepers-2.23.0.jar",
          "size": 1899745,
          "sha512": "9eb01497785f6df530def2355a55f45dcedf3c17601a6a09403eb1d6c20f41badfa7e75636ffd4099aa1667e00f7e824476a1cfe3b186c54c16f8e8877336886",
          "sha256": "20588faf8ac5387eeddc863aeb7b3c581379c160d0b86d2b5358cbeb5c225ab0",
          "sha1": "765720685f65cbe1d7b8102ba535302088acb9d8",
          "md5": "4308c78b227817ed3fca0f8a529e7e17"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.23.0.jar",
          "url": "Shopkeepers-2.23.0.jar",
          "size": 1899745,
          "sha512": "9eb01497785f6df530def2355a55f45dcedf3c17601a6a09403eb1d6c20f41badfa7e75636ffd4099aa1667e00f7e824476a1cfe3b186c54c16f8e8877336886",
          "sha256": "20588faf8ac5387eeddc863aeb7b3c581379c160d0b86d2b5358cbeb5c225ab0",
          "sha1": "765720685f65cbe1d7b8102ba535302088acb9d8",
          "md5": "4308c78b227817ed3fca0f8a529e7e17"
        }
      ]
    }
  ]
}
