{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.17.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.17.2.jar",
          "url": "Shopkeepers-2.17.2.jar",
          "size": 1972453,
          "sha512": "d3fba6cf7951879c0bedbc272255935540b03a25ba7379e031cb26fee08c9ef44da0c5056dc4ef20074bb91e173e80503b8ab30f31bacb72848f2a9e9f5f753e",
          "sha256": "4e1c00e91ad1f07b2ee0d222116503624eea788d04e1214e8c0308a9824fb94e",
          "sha1": "deb135e3260f39fa2c742ab383fd20b0afcd546b",
          "md5": "91867c51bd672402e0efb3935e2544f7"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.17.2"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.17.2.jar",
          "url": "Shopkeepers-2.17.2.jar",
          "size": 1972453,
          "sha512": "d3fba6cf7951879c0bedbc272255935540b03a25ba7379e031cb26fee08c9ef44da0c5056dc4ef20074bb91e173e80503b8ab30f31bacb72848f2a9e9f5f753e",
          "sha256": "4e1c00e91ad1f07b2ee0d222116503624eea788d04e1214e8c0308a9824fb94e",
          "sha1": "deb135e3260f39fa2c742ab383fd20b0afcd546b",
          "md5": "91867c51bd672402e0efb3935e2544f7"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.17.2.jar",
          "url": "Shopkeepers-2.17.2.jar",
          "size": 1972453,
          "sha512": "d3fba6cf7951879c0bedbc272255935540b03a25ba7379e031cb26fee08c9ef44da0c5056dc4ef20074bb91e173e80503b8ab30f31bacb72848f2a9e9f5f753e",
          "sha256": "4e1c00e91ad1f07b2ee0d222116503624eea788d04e1214e8c0308a9824fb94e",
          "sha1": "deb135e3260f39fa2c742ab383fd20b0afcd546b",
          "md5": "91867c51bd672402e0efb3935e2544f7"
        }
      ]
    }
  ]
}
