{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersAPI",
    "version": "2.16.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "ShopkeepersAPI-2.16.1.jar",
          "url": "ShopkeepersAPI-2.16.1.jar",
          "size": 94853,
          "sha512": "28823007c67110d9cf58d8390f7975591a8da6c8f8727c135e8aa598685ec8f83d6f3f78dc1fa9ff503f20c61f5097f227f4560715852474bb255f23b61c46ca",
          "sha256": "af7cdc4648875eea36a8206d8c93db279424aae764b6da48ff210ac9d24ea6f0",
          "sha1": "b9c324a68016122d4cfa13aefa1a447b3efdb915",
          "md5": "38f2b4608c1f92f280548c2059f8a02e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersAPI-2.16.1.jar",
          "url": "ShopkeepersAPI-2.16.1.jar",
          "size": 94853,
          "sha512": "28823007c67110d9cf58d8390f7975591a8da6c8f8727c135e8aa598685ec8f83d6f3f78dc1fa9ff503f20c61f5097f227f4560715852474bb255f23b61c46ca",
          "sha256": "af7cdc4648875eea36a8206d8c93db279424aae764b6da48ff210ac9d24ea6f0",
          "sha1": "b9c324a68016122d4cfa13aefa1a447b3efdb915",
          "md5": "38f2b4608c1f92f280548c2059f8a02e"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersAPI-2.16.1-javadoc.jar",
          "url": "ShopkeepersAPI-2.16.1-javadoc.jar",
          "size": 471291,
          "sha512": "b24ff2c6cb1ebe82ce5357ad215bc6def9293ced3e361be44adbc236abbd14e47cf2a60ea29158d57b93aecc27d6bf1f6195ebaf9e56f789411e2eeae3adb61d",
          "sha256": "87c364ba1db012057492e8f78c47b517e38cd318d4c4aacd68304fb3ae66b9a8",
          "sha1": "ffcc045f365d2be0e07862b80a983eb4493aeaee",
          "md5": "caa4947f632f24742f83f78157ea2689"
        }
      ]
    }
  ]
}
