{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersAPI",
    "version": "2.23.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersExternalAnnotations",
          "version": {
            "requires": "2.23.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersAPI-2.23.4-SNAPSHOT.jar",
          "url": "ShopkeepersAPI-2.23.4-SNAPSHOT.jar",
          "size": 89224,
          "sha512": "df33471931f463a1ead8575a11d0bf9a16fc7df94b4f738127816ea063f9df730a47c80774468d31efa94a3fc13c930c26176f0b9294ae61d52928abe4b65cd1",
          "sha256": "79ce87742ff4f1ea781a2fd59c3cf3b7659963f3e08715d6ccc012080d891ba2",
          "sha1": "8c1ba80fb150d2f18bad24c9fafd0de5582d8dac",
          "md5": "dd5ce92e3ec45d158c9e871929196545"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersExternalAnnotations",
          "version": {
            "requires": "2.23.4-SNAPSHOT"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersAPI-2.23.4-SNAPSHOT.jar",
          "url": "ShopkeepersAPI-2.23.4-SNAPSHOT.jar",
          "size": 89224,
          "sha512": "df33471931f463a1ead8575a11d0bf9a16fc7df94b4f738127816ea063f9df730a47c80774468d31efa94a3fc13c930c26176f0b9294ae61d52928abe4b65cd1",
          "sha256": "79ce87742ff4f1ea781a2fd59c3cf3b7659963f3e08715d6ccc012080d891ba2",
          "sha1": "8c1ba80fb150d2f18bad24c9fafd0de5582d8dac",
          "md5": "dd5ce92e3ec45d158c9e871929196545"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersAPI-2.23.4-SNAPSHOT-javadoc.jar",
          "url": "ShopkeepersAPI-2.23.4-SNAPSHOT-javadoc.jar",
          "size": 485362,
          "sha512": "cc5223115d2616f8c1e5a3ea84d81b93ce5485c9f63ff90ac66db338c4b5bc3a70d785bfa9e0acf7016f4d85cfa4b2c9e4df87115cab2ef28cc4760d121e8e3f",
          "sha256": "861f26f446ceeea2d31558a3e4613a5223980d1a19031ba0d04fdf6b5998ca53",
          "sha1": "0fec182d0734150376289ed6863bfdc954bc2b34",
          "md5": "4ce23de62b90a8c1b03c635620843a36"
        }
      ]
    }
  ]
}
