{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.17.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.17.1.jar",
          "url": "Shopkeepers-2.17.1.jar",
          "size": 1972372,
          "sha512": "388ed7fc2dd42f8ff29387be2b02b4c9de2036f3e884c41647f10741ce18f5b15f46fe36b317e6f69b21d6a3f31033d209c0152a20f6a8c8d94a07a1b9584253",
          "sha256": "b7fe08f4e46514ca05235f703cb3e3634cf942dcb13251eaf970d41cce23e932",
          "sha1": "cdb754a9b44db68a5b2d17e8caa35ae2b63e69cf",
          "md5": "3cd083a40167003e5cb5454bfcd0a7b6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.17.1"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.17.1.jar",
          "url": "Shopkeepers-2.17.1.jar",
          "size": 1972372,
          "sha512": "388ed7fc2dd42f8ff29387be2b02b4c9de2036f3e884c41647f10741ce18f5b15f46fe36b317e6f69b21d6a3f31033d209c0152a20f6a8c8d94a07a1b9584253",
          "sha256": "b7fe08f4e46514ca05235f703cb3e3634cf942dcb13251eaf970d41cce23e932",
          "sha1": "cdb754a9b44db68a5b2d17e8caa35ae2b63e69cf",
          "md5": "3cd083a40167003e5cb5454bfcd0a7b6"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.17.1.jar",
          "url": "Shopkeepers-2.17.1.jar",
          "size": 1972372,
          "sha512": "388ed7fc2dd42f8ff29387be2b02b4c9de2036f3e884c41647f10741ce18f5b15f46fe36b317e6f69b21d6a3f31033d209c0152a20f6a8c8d94a07a1b9584253",
          "sha256": "b7fe08f4e46514ca05235f703cb3e3634cf942dcb13251eaf970d41cce23e932",
          "sha1": "cdb754a9b44db68a5b2d17e8caa35ae2b63e69cf",
          "md5": "3cd083a40167003e5cb5454bfcd0a7b6"
        }
      ]
    }
  ]
}
