{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersMain",
    "version": "2.28.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.28.1"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.28.1.jar",
          "url": "ShopkeepersMain-2.28.1.jar",
          "size": 2242493,
          "sha512": "3de998ec89bdc1594e1970efc5ec0d727549c203cf415263bc275f154f317302c92e28933479640ca9eb95c1933c646990e786b3f1adb0daf5c1508a5c2fb82d",
          "sha256": "883aa7b459f8b4105596770410779d82ea3a42e64440d8ffeb0069f8e87a15a6",
          "sha1": "e38ab558229449b7febf3304f6fa10ae987aa382",
          "md5": "de13fdf7dcc3883cd4ed77887e9c3343"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.28.1"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "com.sk89q.worldedit.worldedit-libs",
              "module": "core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.28.1.jar",
          "url": "ShopkeepersMain-2.28.1.jar",
          "size": 2242493,
          "sha512": "3de998ec89bdc1594e1970efc5ec0d727549c203cf415263bc275f154f317302c92e28933479640ca9eb95c1933c646990e786b3f1adb0daf5c1508a5c2fb82d",
          "sha256": "883aa7b459f8b4105596770410779d82ea3a42e64440d8ffeb0069f8e87a15a6",
          "sha1": "e38ab558229449b7febf3304f6fa10ae987aa382",
          "md5": "de13fdf7dcc3883cd4ed77887e9c3343"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersMain-2.28.1.jar",
          "url": "ShopkeepersMain-2.28.1.jar",
          "size": 2242493,
          "sha512": "3de998ec89bdc1594e1970efc5ec0d727549c203cf415263bc275f154f317302c92e28933479640ca9eb95c1933c646990e786b3f1adb0daf5c1508a5c2fb82d",
          "sha256": "883aa7b459f8b4105596770410779d82ea3a42e64440d8ffeb0069f8e87a15a6",
          "sha1": "e38ab558229449b7febf3304f6fa10ae987aa382",
          "md5": "de13fdf7dcc3883cd4ed77887e9c3343"
        }
      ]
    }
  ]
}
