{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersMain",
    "version": "2.26.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.26.0"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.26.0.jar",
          "url": "ShopkeepersMain-2.26.0.jar",
          "size": 2106229,
          "sha512": "c9644407723d1698e65be341605daf5087be6348ad02b9a25c1bf1e455d9042aea56ae79d65111408b683410437c50907242fd003957bdaf49f945b00e4500bd",
          "sha256": "bdbc9cf821a8152c22d887b2368b54f178997e73d26ebb704d3f85eecf8da828",
          "sha1": "14143f093e8d54120a63954fe09fb3f3c251823f",
          "md5": "5ac793ee53d0fdddeb7422313938959e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.26.0"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "com.sk89q.worldedit.worldedit-libs",
              "module": "core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.26.0.jar",
          "url": "ShopkeepersMain-2.26.0.jar",
          "size": 2106229,
          "sha512": "c9644407723d1698e65be341605daf5087be6348ad02b9a25c1bf1e455d9042aea56ae79d65111408b683410437c50907242fd003957bdaf49f945b00e4500bd",
          "sha256": "bdbc9cf821a8152c22d887b2368b54f178997e73d26ebb704d3f85eecf8da828",
          "sha1": "14143f093e8d54120a63954fe09fb3f3c251823f",
          "md5": "5ac793ee53d0fdddeb7422313938959e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersMain-2.26.0.jar",
          "url": "ShopkeepersMain-2.26.0.jar",
          "size": 2106229,
          "sha512": "c9644407723d1698e65be341605daf5087be6348ad02b9a25c1bf1e455d9042aea56ae79d65111408b683410437c50907242fd003957bdaf49f945b00e4500bd",
          "sha256": "bdbc9cf821a8152c22d887b2368b54f178997e73d26ebb704d3f85eecf8da828",
          "sha1": "14143f093e8d54120a63954fe09fb3f3c251823f",
          "md5": "5ac793ee53d0fdddeb7422313938959e"
        }
      ]
    }
  ]
}
