{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.16.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.16.0.jar",
          "url": "Shopkeepers-2.16.0.jar",
          "size": 1943462,
          "sha512": "20f8ba076266951ca3ab8e8593bb0a7745b33e97a5193e64613ce8f97b40253fae6df0765412ec72660ff5e26074e33093e68ef3d53cca804fb96907418e91a0",
          "sha256": "704e60e8017349b1d6a96b7d73dd9e9858a3ff1e35c9f358962d1000c0ff1808",
          "sha1": "4ea09b44c85208045f7757498a2bbd0a2f7231a0",
          "md5": "1dc6f2425df729f22f9e012da9bc8b48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.16.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.16.0.jar",
          "url": "Shopkeepers-2.16.0.jar",
          "size": 1943462,
          "sha512": "20f8ba076266951ca3ab8e8593bb0a7745b33e97a5193e64613ce8f97b40253fae6df0765412ec72660ff5e26074e33093e68ef3d53cca804fb96907418e91a0",
          "sha256": "704e60e8017349b1d6a96b7d73dd9e9858a3ff1e35c9f358962d1000c0ff1808",
          "sha1": "4ea09b44c85208045f7757498a2bbd0a2f7231a0",
          "md5": "1dc6f2425df729f22f9e012da9bc8b48"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.16.0.jar",
          "url": "Shopkeepers-2.16.0.jar",
          "size": 1943462,
          "sha512": "20f8ba076266951ca3ab8e8593bb0a7745b33e97a5193e64613ce8f97b40253fae6df0765412ec72660ff5e26074e33093e68ef3d53cca804fb96907418e91a0",
          "sha256": "704e60e8017349b1d6a96b7d73dd9e9858a3ff1e35c9f358962d1000c0ff1808",
          "sha1": "4ea09b44c85208045f7757498a2bbd0a2f7231a0",
          "md5": "1dc6f2425df729f22f9e012da9bc8b48"
        }
      ]
    }
  ]
}
