{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersAPI",
    "version": "2.23.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersExternalAnnotations",
          "version": {
            "requires": "2.23.5"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersAPI-2.23.5.jar",
          "url": "ShopkeepersAPI-2.23.5.jar",
          "size": 89198,
          "sha512": "fe9fec4b1f8ec2bf5d3fb1ce03a7319a095ac4c4fed544a87155e9c623a796ff4202f06b19562c4480c2e30f88c7d561257febbf9cf8d67b6d6a636d4873995d",
          "sha256": "cd14f4c3ac32aeeebd49c7c1ac50f662d6c2da8c536f8c2343783d9b5ffc97ea",
          "sha1": "094921a248f4433b6ea9503ecadbfaefd29c887a",
          "md5": "10fe26b5f96b7757f24a2386626281f0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersExternalAnnotations",
          "version": {
            "requires": "2.23.5"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersAPI-2.23.5.jar",
          "url": "ShopkeepersAPI-2.23.5.jar",
          "size": 89198,
          "sha512": "fe9fec4b1f8ec2bf5d3fb1ce03a7319a095ac4c4fed544a87155e9c623a796ff4202f06b19562c4480c2e30f88c7d561257febbf9cf8d67b6d6a636d4873995d",
          "sha256": "cd14f4c3ac32aeeebd49c7c1ac50f662d6c2da8c536f8c2343783d9b5ffc97ea",
          "sha1": "094921a248f4433b6ea9503ecadbfaefd29c887a",
          "md5": "10fe26b5f96b7757f24a2386626281f0"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersAPI-2.23.5-javadoc.jar",
          "url": "ShopkeepersAPI-2.23.5-javadoc.jar",
          "size": 484167,
          "sha512": "46e1b9dc69f33a5fd945e78cdf1d81a2e020df2cc5ce4ae279463b73f040ec51e0bb4e7b3a31d1d08c6537541ac254f06315d7d19204a5f58d565c1c375c43cf",
          "sha256": "aa6e72e4d70c9b3e1de3524de479ad4fa237b85ded49b3356d17b95f665eb096",
          "sha1": "23301c6560209a5c5186cc53f73f7b2b4d603ac3",
          "md5": "953a14ec4d68c76ea740065460fdebb3"
        }
      ]
    }
  ]
}
