{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.22.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.22.0.jar",
          "url": "Shopkeepers-2.22.0.jar",
          "size": 1922292,
          "sha512": "c4d53aa21ac7ea8694e9dbc26751ccf9a9a1e588cf5dee57eb52dc3f1b6425811a351757b265fee34d98c1ba9c1626be933c83926155b4963eb45530fb938e0c",
          "sha256": "d69851eaba87e1184b4986e5860e2b6c60ba1f73b926fe228b9fdaaf9ae8e58a",
          "sha1": "ef0cf53cc49e17fab0247438d605976ebc67f1c9",
          "md5": "b2a28a9f6c26fee98b167f4736fb6f7b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.22.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.22.0.jar",
          "url": "Shopkeepers-2.22.0.jar",
          "size": 1922292,
          "sha512": "c4d53aa21ac7ea8694e9dbc26751ccf9a9a1e588cf5dee57eb52dc3f1b6425811a351757b265fee34d98c1ba9c1626be933c83926155b4963eb45530fb938e0c",
          "sha256": "d69851eaba87e1184b4986e5860e2b6c60ba1f73b926fe228b9fdaaf9ae8e58a",
          "sha1": "ef0cf53cc49e17fab0247438d605976ebc67f1c9",
          "md5": "b2a28a9f6c26fee98b167f4736fb6f7b"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.22.0.jar",
          "url": "Shopkeepers-2.22.0.jar",
          "size": 1922292,
          "sha512": "c4d53aa21ac7ea8694e9dbc26751ccf9a9a1e588cf5dee57eb52dc3f1b6425811a351757b265fee34d98c1ba9c1626be933c83926155b4963eb45530fb938e0c",
          "sha256": "d69851eaba87e1184b4986e5860e2b6c60ba1f73b926fe228b9fdaaf9ae8e58a",
          "sha1": "ef0cf53cc49e17fab0247438d605976ebc67f1c9",
          "md5": "b2a28a9f6c26fee98b167f4736fb6f7b"
        }
      ]
    }
  ]
}
