{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersExternalAnnotations",
    "version": "2.28.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jdt",
          "module": "org.eclipse.jdt.annotation",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vegardit.no-npe",
          "module": "no-npe-eea-java-21",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.28.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.28.0.jar",
          "size": 39390,
          "sha512": "6873f188a6855080b18fb597987bcb77963cf6bfa37b7116128df2de62a50bfa98308c792a723b5b26a7509056979813293fa8211f4383be595be71ff771cf0b",
          "sha256": "3d312965bd72ad8d28682db6466e86bf8a37d8a05b690d87722db6fdd8606386",
          "sha1": "9b387245b4deb0c75ccbada57d5eb54bc8660d21",
          "md5": "90515708297fecd2bc5827a7eae2ce7a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.28.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.28.0.jar",
          "size": 39390,
          "sha512": "6873f188a6855080b18fb597987bcb77963cf6bfa37b7116128df2de62a50bfa98308c792a723b5b26a7509056979813293fa8211f4383be595be71ff771cf0b",
          "sha256": "3d312965bd72ad8d28682db6466e86bf8a37d8a05b690d87722db6fdd8606386",
          "sha1": "9b387245b4deb0c75ccbada57d5eb54bc8660d21",
          "md5": "90515708297fecd2bc5827a7eae2ce7a"
        }
      ]
    }
  ]
}
