{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersExternalAnnotations",
    "version": "2.25.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jdt",
          "module": "org.eclipse.jdt.annotation",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vegardit.no-npe",
          "module": "no-npe-eea-java-21",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.25.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.25.0.jar",
          "size": 38691,
          "sha512": "2e4c452ac684ee80ca806a395c0e80974b60ca658ae0902d46626b5ce501c2b747b0b455e75acbc0d0aa06e19e90bb91cc0ce3ac40973f92a46ef81fab6289cf",
          "sha256": "2124683fe24d094397220ebb4d8e0c61ebfb12d6e12fec076c3d7e7f26d174f8",
          "sha1": "e626b608265d64be95f3e7ed1b10127be373cf41",
          "md5": "273d7df6696890dcb953b30ec54d75f6"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.25.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.25.0.jar",
          "size": 38691,
          "sha512": "2e4c452ac684ee80ca806a395c0e80974b60ca658ae0902d46626b5ce501c2b747b0b455e75acbc0d0aa06e19e90bb91cc0ce3ac40973f92a46ef81fab6289cf",
          "sha256": "2124683fe24d094397220ebb4d8e0c61ebfb12d6e12fec076c3d7e7f26d174f8",
          "sha1": "e626b608265d64be95f3e7ed1b10127be373cf41",
          "md5": "273d7df6696890dcb953b30ec54d75f6"
        }
      ]
    }
  ]
}
