{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.24.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.24.0.jar",
          "url": "Shopkeepers-2.24.0.jar",
          "size": 2180784,
          "sha512": "5f89097a0b04e14a764ce4b53c39ef2c2d6d976129fcc250ee78523a3581d0be35d439dcafe41dc7265a09d707b70732af3505f0c7d6455a264d3c47d2876d60",
          "sha256": "a411e63a17c28bb711a1ef88bb4d3a8d11a0540ed3a21133620d0c876d964923",
          "sha1": "672e37a154967fda6996da149571b270a23edafe",
          "md5": "7afa446398bfdbec02640ff491a2536e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.24.0"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.24.0.jar",
          "url": "Shopkeepers-2.24.0.jar",
          "size": 2180784,
          "sha512": "5f89097a0b04e14a764ce4b53c39ef2c2d6d976129fcc250ee78523a3581d0be35d439dcafe41dc7265a09d707b70732af3505f0c7d6455a264d3c47d2876d60",
          "sha256": "a411e63a17c28bb711a1ef88bb4d3a8d11a0540ed3a21133620d0c876d964923",
          "sha1": "672e37a154967fda6996da149571b270a23edafe",
          "md5": "7afa446398bfdbec02640ff491a2536e"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.24.0.jar",
          "url": "Shopkeepers-2.24.0.jar",
          "size": 2180784,
          "sha512": "5f89097a0b04e14a764ce4b53c39ef2c2d6d976129fcc250ee78523a3581d0be35d439dcafe41dc7265a09d707b70732af3505f0c7d6455a264d3c47d2876d60",
          "sha256": "a411e63a17c28bb711a1ef88bb4d3a8d11a0540ed3a21133620d0c876d964923",
          "sha1": "672e37a154967fda6996da149571b270a23edafe",
          "md5": "7afa446398bfdbec02640ff491a2536e"
        }
      ]
    }
  ]
}
