{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersExternalAnnotations",
    "version": "2.27.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jdt",
          "module": "org.eclipse.jdt.annotation",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "com.vegardit.no-npe",
          "module": "no-npe-eea-java-21",
          "version": {
            "requires": "1.3.5"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.27.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.27.0.jar",
          "size": 39391,
          "sha512": "6a080df11803c1153a9d7b73c4d6b36d81b0e16927867ddca11f94dbd07a7376452b0af6ce63c370e3f48f0a3cb870b6a9b89c27650a1fbaf5350f31ec97e565",
          "sha256": "eb13025f86b2a37eacc5ece69d722da31dec32c87abcc688e03d7ce3f6b2a5e8",
          "sha1": "7500eea26cc743e2b304dcf6ba18303abe83a2a9",
          "md5": "77f7157e3f3e5063c0ccb917d8539923"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersExternalAnnotations-2.27.0.jar",
          "url": "ShopkeepersExternalAnnotations-2.27.0.jar",
          "size": 39391,
          "sha512": "6a080df11803c1153a9d7b73c4d6b36d81b0e16927867ddca11f94dbd07a7376452b0af6ce63c370e3f48f0a3cb870b6a9b89c27650a1fbaf5350f31ec97e565",
          "sha256": "eb13025f86b2a37eacc5ece69d722da31dec32c87abcc688e03d7ce3f6b2a5e8",
          "sha1": "7500eea26cc743e2b304dcf6ba18303abe83a2a9",
          "md5": "77f7157e3f3e5063c0ccb917d8539923"
        }
      ]
    }
  ]
}
