{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "Shopkeepers",
    "version": "2.23.4-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.23.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.23.4-SNAPSHOT.jar",
          "url": "Shopkeepers-2.23.4-SNAPSHOT.jar",
          "size": 1986047,
          "sha512": "4c7244427e2374a3ee9490e184947d5f825e2fe42e4bc69e6cc1d928fb3e2876b2b40601301a36108c36203e1016c51c6d9460cfdf51c2ce43d1f8e4baa15466",
          "sha256": "749f53ee5c4ea1f2d5a290caa4c3f4dfc2b196147de42fdb72f4802f66858d31",
          "sha1": "755f57dbf4eb899993b5760f9b576630ce474995",
          "md5": "a1f97bdd7a93b49fb0b6964971e65e94"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersMain",
          "version": {
            "requires": "2.23.4-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "Shopkeepers-2.23.4-SNAPSHOT.jar",
          "url": "Shopkeepers-2.23.4-SNAPSHOT.jar",
          "size": 1986047,
          "sha512": "4c7244427e2374a3ee9490e184947d5f825e2fe42e4bc69e6cc1d928fb3e2876b2b40601301a36108c36203e1016c51c6d9460cfdf51c2ce43d1f8e4baa15466",
          "sha256": "749f53ee5c4ea1f2d5a290caa4c3f4dfc2b196147de42fdb72f4802f66858d31",
          "sha1": "755f57dbf4eb899993b5760f9b576630ce474995",
          "md5": "a1f97bdd7a93b49fb0b6964971e65e94"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "Shopkeepers-2.23.4-SNAPSHOT.jar",
          "url": "Shopkeepers-2.23.4-SNAPSHOT.jar",
          "size": 1986047,
          "sha512": "4c7244427e2374a3ee9490e184947d5f825e2fe42e4bc69e6cc1d928fb3e2876b2b40601301a36108c36203e1016c51c6d9460cfdf51c2ce43d1f8e4baa15466",
          "sha256": "749f53ee5c4ea1f2d5a290caa4c3f4dfc2b196147de42fdb72f4802f66858d31",
          "sha1": "755f57dbf4eb899993b5760f9b576630ce474995",
          "md5": "a1f97bdd7a93b49fb0b6964971e65e94"
        }
      ]
    }
  ]
}
