{
  "formatVersion": "1.1",
  "component": {
    "group": "com.nisovin.shopkeepers",
    "module": "ShopkeepersMain",
    "version": "2.23.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.23.5"
          }
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.23.5.jar",
          "url": "ShopkeepersMain-2.23.5.jar",
          "size": 1927426,
          "sha512": "a582953cae7a4a233a2dea7ccb3c4cdf21d5fd1cf1d779a6b0ebba12d733630fa8eba2766939c5b75a0e2d2484a8430138fb3b91da6c46862b04fd4f4b9aa76c",
          "sha256": "55428da4633183efb77086f38a710cef243bcaae15f157d41e03a6fb7aa20796",
          "sha1": "780dec72648298c1c525987738e4fa6da78bf7ad",
          "md5": "7b05fe221b3579c639aceb35d077a9fd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.nisovin.shopkeepers",
          "module": "ShopkeepersAPI",
          "version": {
            "requires": "2.23.5"
          },
          "excludes": [
            {
              "group": "commons-lang",
              "module": "commons-lang"
            },
            {
              "group": "com.google.code.findbugs",
              "module": "jsr305"
            },
            {
              "group": "com.sk89q.worldedit.worldedit-libs",
              "module": "core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "ShopkeepersMain-2.23.5.jar",
          "url": "ShopkeepersMain-2.23.5.jar",
          "size": 1927426,
          "sha512": "a582953cae7a4a233a2dea7ccb3c4cdf21d5fd1cf1d779a6b0ebba12d733630fa8eba2766939c5b75a0e2d2484a8430138fb3b91da6c46862b04fd4f4b9aa76c",
          "sha256": "55428da4633183efb77086f38a710cef243bcaae15f157d41e03a6fb7aa20796",
          "sha1": "780dec72648298c1c525987738e4fa6da78bf7ad",
          "md5": "7b05fe221b3579c639aceb35d077a9fd"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "ShopkeepersMain-2.23.5.jar",
          "url": "ShopkeepersMain-2.23.5.jar",
          "size": 1927426,
          "sha512": "a582953cae7a4a233a2dea7ccb3c4cdf21d5fd1cf1d779a6b0ebba12d733630fa8eba2766939c5b75a0e2d2484a8430138fb3b91da6c46862b04fd4f4b9aa76c",
          "sha256": "55428da4633183efb77086f38a710cef243bcaae15f157d41e03a6fb7aa20796",
          "sha1": "780dec72648298c1c525987738e4fa6da78bf7ad",
          "md5": "7b05fe221b3579c639aceb35d077a9fd"
        }
      ]
    }
  ]
}
